apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: notes-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: salehktk005/notes-app-frontend:1.0

        ports:
        - containerPort: 80

        env:
        - name: frontend-configmap
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: key

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"

          limits:
            memory: "128Mi"
            cpu: "500m"
