FROM jenkins/jenkins:lts

USER root

# Install tools
RUN apt-get update && \
    apt-get install -y wget curl apt-transport-https gnupg lsb-release

# Install Trivy
RUN wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb && \
    dpkg -i trivy_0.50.0_Linux-64bit.deb

USER jenkins